### ISSUE TITLE
Allow empty lines before declarations

### ISSUE THREAD

**Issue by sobolevn** [wemake-services/stylelint-config-strict-scss#2]
This code:

```scss
  .comments-action-reload {
      $button-color: #409eff;
      $button-text-color: #fff;

      display: inline-block;
      cursor: pointer;
      outline: none;

      padding: 12px 20px;
      color: $button-text-color;
      background-color: $button-color;
      border-color: $button-color;
   }
```

Raises this error:

```
client/pages/index.vue
 106:7  ✖  Unexpected empty line before           declaration-empty-line-before
           declaration
```

And I don't like it.
